name: 'Access Token'
description: 'Generate Github Access Token By app'
inputs:
  github_app_id:
    description: 'App Id'
    required: true
  github_installation_id:
    description: 'Installation ID'
    required: true
  pem_key:
    description: 'Private key'
    required: true
runs:
  using: composite
  steps:

  - name: Configurar Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.x'

  - name: Generate JWT and get access token
    shell: bash
    env:
      APP_ID: ${{ inputs.github_app_id }}
      INSTALLATION_ID: ${{ inputs.github_installation_id }}
      PRIVATE_KEY: ${{ inputs.pem_key }}
    run: python code/.github/scripts/generate_token.py/generate_token.py
